server:
  port: 8118

spring:
  application:
    name: doudizhu-backend

  # Database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddz?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ddz
    password: cCjANasc75Bx2y4N

logging:
  level:
    com.game.doudizhu: DEBUG
    org.springframework.web.socket: DEBUG

